### ISSUE TITLE
README doesn't mention that scrypt.hash requires a salt parameter

### ISSUE THREAD

**Issue by g-p-g** [barrysteyn/node-scrypt#105] opened 2015-10-12 16:26 UTC
The README seems to be out of date as it describes only 3 required parameters, while 4 are needed.

**Comment by barrysteyn** [comment] 2015-10-12 18:16
Thanks for bringing this up. It is not that the README is out of date, the problem is that when I updated the module, I forgot to update the salt requirement for the hash. Will ameliorate now. Thanks.

**Comment by barrysteyn** [comment] 2015-10-12 18:32
fixed in a1b8b52414feee13a3c2e080c201de792efe06a6

**Closed by barrysteyn** 2015-10-12 18:32 UTC

**Comment by g-p-g** [comment] 2015-10-12 22:45
Thanks for fixing, but mentioning that the salt can be empty is too vague. Does that mean the function will generate a salt and return it, or just that an empty salt will be used? To follow the same style as the other params you could just leave out that last part.
