### ISSUE TITLE
Cryptography functionality

### ISSUE THREAD

**Issue by alemhnan** [barrysteyn/node-scrypt#102] opened 2015-10-04 10:02 UTC
In issue #22 you removed cryptographic functionality. 

I understand that it's not in the roadmap and neither a priority, but do you have any plans to reintroduce that feature? Do you have any suggestion on how to implement that in my own code otherwise?

**Comment by barrysteyn** [comment] 2015-10-06 20:44
Hi

What I was thinking was making two modules, the crypto module would depend on this one. The thing is, I think lots of people lost interest. You are the first person who has asked me about it.

What are you thinking of using it for and why?

**Comment by alemhnan** [comment] 2015-10-07 10:18
Hi @barrysteyn,

The general use case is of course to encrypt/decrypt text with a master password. In my specific case  I am developing a personalizable web interface for mongodb. I want the end user to store the database connection strings in my system and I would like to save them encrypted using a password provided by the user.

Without this feature in node-scrypt I will have to use the standard [crypto](https://nodejs.org/api/crypto.html) as seen [here](http://lollyrock.com/articles/nodejs-encryption).

As you see it's not a vital feature (at least it's easily replaceable), but it is very nice to use scrypt for this use case as well.

**Comment by barrysteyn** [comment] 2015-10-09 01:00
Okay, I understand the functionality. It is not too difficult to put it back in, the problem is the time. I will put it on the roadmap, but if I have to be honest, it wouldn't be anytime this year that I will get around to implementing it.

**Comment by barrysteyn** [comment] 2015-10-09 21:43
I am going to close this issue - but I will reopen it if I decide to do the crypto functionality.

**Closed by barrysteyn** 2015-10-09 21:43 UTC
