### ISSUE TITLE
Can't install node-scrypt on iojs v3.0.0

### ISSUE THREAD

**Issue by tresdin** [barrysteyn/node-scrypt#82] opened 2015-08-12 15:14 UTC
I've tried to install node scrypt on iojs v3.0.0 and it fails on `node-gyp rebuild` stage. Is there any work around for this issue?

**Comment by barrysteyn** [comment] 2015-08-12 15:22
Hi Lewis

v 3.0.0 is very new. I should be able to fix the problem - give me two or so days to look into it.

Thanks for brining this up.

**Comment by barrysteyn** [comment] 2015-08-12 15:28
Actually, just took a very quick look at this. The problem is the NAN abstraction layer. It needs to be updated by the makers of Iojs. They will definitely do this very soon (I am actually in contact with them, so I will ask them personally when it will be updated). Until then, there is not much I can do...

I will leave this issue open as a reminder for me to follow up with them.

**Comment by tresdin** [comment] 2015-08-12 15:52
Thanks for your information @barrysteyn . FYI, iojs team seems to underestimate the importance of *Beta* stage. :)

**Comment by alex94puchades** [comment] 2015-08-13 20:25
I'm getting node-gyp errors with node 0.12 also, maybe it is related?

**Comment by barrysteyn** [comment] 2015-09-01 16:01
Hi - try clone branch V5, and see if things work. I have updated the module to use Nan V 2.x, and this should solve the issue. Please report back. FYI: Version 5 (the branch I am asking you to clone) will be released sometime this week or early next week.

**Comment by barrysteyn** [comment] 2015-09-03 15:50
I am closing this issue as it should not still be causing problems.

**Closed by barrysteyn** 2015-09-03 15:50 UTC
